In [1]:
import numpy as np
import pandas as pd

Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
reversed_arr

array([5, 4, 3, 2, 1])

Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatten = array1.flatten()
flatten

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

arr1 == arr2

array([[ True,  True],
       [ True,  True]])

Find the most frequent value and their indice(s) in the following arrays: 

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print('max ferq', np.bincount(x).argmax())
print()
for i in range(len(x)):
    if x[i] == np.bincount(x).argmax():
        print(i)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3 ])
print('max ferq', np.bincount(y).argmax())
print()
for i in range(len(y)):
    if y[i] == np.bincount(y).argmax():
        print(i)

max ferq 1

0
5
7
8
9
max ferq 1

0
1
2


For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise


In [17]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print()
print(gfg.sum(axis=1))
print()
print(gfg.sum(axis=0))

45

[[14]
 [16]
 [15]]

[[20  9 16]]


For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [25]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))
print("eigen values ",np.linalg.eig(n_array)[0])
print("eigen vectors ",np.linalg.eig(n_array)[1])
print("inv ", np.linalg.inv(n_array))
print("det ", np.linalg.det(n_array))


176
eigen values  [98.16835147 28.097044   49.73460452]
eigen vectors  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inv  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
det  137180.0000000001


Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]


ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [32]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

print(np.dot(p1, q1))
print(np.cov(p1.transpose(), q1.transpose()))

[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [43]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x, y))
print()
print(np.outer(x, y))
print()
print(np.array(np.meshgrid(x.flatten(), y.flatten())).transpose().reshape(-1, 2))

[[17 52]
 [13 62]]

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])


i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [50]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

print(np.abs(array))
print()
print(np.percentile(array, [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis=0))
print(np.percentile(array, [25, 50, 75], axis=1))
print()
print("mean: ", array.mean(), "median : ",np.median(array),"std: ", array.std())
print("mean: ", array.mean(axis=0),"median: ", np.median(array, axis=0),"std: ", array.std(axis=0))
print("mean: ",array.mean(axis=1),"median: ", np.median(array, axis=1),"std: ", array.std(axis=1))


[[1 2 3]
 [4 5 6]]

[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

mean:  -0.5 median :  -0.5 std:  3.8622100754188224
mean:  [-1.5  1.5 -1.5] median:  [-1.5  1.5 -1.5] std:  [2.5 3.5 4.5]
mean:  [ 0.66666667 -1.66666667] median:  [ 1. -4.] std:  [2.05480467 4.78423336]


For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [53]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find


i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [58]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])


[1.  1.2 2.  2.  2.2 3. ]
[0 1 3 5 2 4]
[1.  1.2 2.  2. ]
[1.2 2.  2.  2.2 3. ]


For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find


i. Integer elements only

ii. Float elements only

In [60]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print( array[array == array.astype(int)])
print( array[array == array.astype(float)])

[1. 2. 3. 2.]
[1.  1.2 2.2 2.  3.  2. ]


Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [61]:
import cv2

In [ ]:
def img_to_array(path):
    img = cv2.imread(path)
    if len(img.shape) == 2:
        np.savetxt("grayscaleimage.txt", img, fmt='%d')
    else:
        for i in range(3):
            np.savetxt(f"channel_{i}.txt", img[:,:,i], fmt='%d')

In [66]:
path = '/Users/anmol117/Desktop/Screenshot 2025-05-24 at 7.24.28 PM.png'\

img_to_array(path)

Load the saved file into jupyter notebook?

In [72]:
#grey = np.loadtxt("grayscaleimage.txt", dtype=int)

r = np.loadtxt("channel_0.txt", dtype=int)
g = np.loadtxt("channel_1.txt", dtype=int)
b = np.loadtxt("channel_2.txt", dtype=int)

r, g, b

(array([[  0,   0,   0, ...,  43,  17,   3],
        [  0,   0,   0, ...,  94,  79,  55],
        [  0,   0,   0, ..., 108, 104,  96],
        ...,
        [141, 143, 145, ...,  72,  72,  70],
        [134, 132, 139, ...,  71,  71,  70],
        [131, 128, 135, ...,  69,  69,  68]]),
 array([[  0,   0,   0, ...,  38,  16,   3],
        [  0,   0,   0, ...,  82,  69,  49],
        [  0,   0,   0, ...,  93,  90,  84],
        ...,
        [154, 156, 158, ...,  90,  90,  89],
        [147, 146, 153, ...,  89,  89,  88],
        [143, 141, 148, ...,  87,  87,  87]]),
 array([[  0,   0,   0, ...,  36,  15,   3],
        [  0,   0,   0, ...,  78,  67,  46],
        [  0,   0,   0, ...,  89,  86,  79],
        ...,
        [164, 167, 169, ..., 105, 106, 105],
        [156, 155, 162, ..., 104, 105, 104],
        [152, 150, 157, ..., 104, 104, 104]]))